apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: schemas.mysql.sample.javaoperatorsdk
spec:
  group: mysql.sample.javaoperatorsdk
  version: v1
  scope: Namespaced
  names:
    plural: schemas
    singular: schema
    kind: MySQLSchema
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            encoding:
              type: string